spring.application.name=ocr

spring.datasource.url=jdbc:postgresql://localhost:5433/${POSTGRES_DB:ocr}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type.json_format_mapper=jackson

ocr.tessdata.path=tessdata
ocr.tessdata.language=eng
ocr.debug-images=false

ocr.uploads.path=uploads

ocr.custom.executable=neural_net/ocr_nn.exe
ocr.custom.weights=neural_net/net_weights.txt
ocr.custom.timeout-seconds=30