spring.application.name=ocr

tesseract.datapath=${TESSDATA_PATH:}
tesseract.language=en

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/ocr}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
